### ISSUE TITLE
Request for clarity around Licensing

### ISSUE THREAD

**Issue by bigbitbus** [wsvincent/drf-todo-api#3]
Hi there,

I am interested in using the code contained in these examples in a commercial setting; before doing so I wanted to read the license attached to the repo.

Could you please clarify this.

Thanks!

**Comment by wsvincent** [comment]
Hi @bigbitbus,

Thanks for your question. I've added the appropriate license, which is MIT, to the repo. Enjoy!

-Will

**Comment by bigbitbus** [comment]
Thanks! This is very helpful.

For anyone curious about the terms of the MIT license: https://tldrlegal.com/license/mit-license
